GET https://offer-service-sh3jxse7bq-ew.a.run.app/rest/v1/offers
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0ZGVhbGVyQHRydWNrb28uY29tIiwiZXhwIjoxNjI1MjQwODUzLCJpYXQiOjE2MjUyNDA4NTMsImNsYWltcyI6WyJkZWFsZXIiLCJ3b3Jrc2hvcCJdfQ.d_Z7SRCNC8JEooXxy9JRTuWLf8forlAxxN-OLuPlb_B6LotQdQhisb4LrI3eUxduHtAxXEy4HiwqFYD3Gnva2-lOVO9SU461Fm4BamGAuaz2V-VHQtsDXHQn2CsKiFv2lcIM3E9DQO9eUAZj-45zaUSbBbyaxf03wRsIdnwudHkHUHz7wDtuViI58mB40sOBEZxWnKIZ-WhINahTS54dyvYd1QUjFxGM_XwMTm31SfDbdOBfeticdYXTy_KGg9DH5N_VbgHgQT-aQvVMZMmz-WlqyfvrE8STEzw0LDs9i2p9-tIAkUVrcmGK-cDJmqaiuuMirrHo407Pr6DIUr4pjA'